language: php
sudo: "required"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

warnings_are_errors: false

services:
  - "docker"

before_install:
  - make setup

install:
  - "make install-project"

script:
  - "make test"
  - "make image"

php:
  - 7.3

after_success:
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"; docker push kabaconde/symfony-devops; fi

notifications:
  email: false
