language: php
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - IMAGE_NAME=kabaconde/devops

before_install:
  - make setup

install:
  - make install-project

before_script:
  - version=$TRAVIS_JOB_ID

script:
  - make test
  - docker build --tag "$IMAGE_NAME" -f ./docker/apache-prod/Dockerfile .

after_script:
  - docker images
  - echo $TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" && \
    docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest" && \
    docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}" && \
    docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
    fi
