language: shell
sudo: "required"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

warnings_are_errors: false

services:
  - "docker"

# before_install:
#   - make setup

# install:
#   - "make install-project"

script:
#   - "make test"
#   - "make image"
    - echo $DOCKER_PASSWORD
    # - echo $OCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
    # - docker push kabaconde/symfony-devops

# php:
#   - 7.3

after_success:
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo $DOCKER_LOGIN
  - echo $DOCKER_PASSWORD
  - docker build -t kabaconde/symfony-devops ./docker/apache
  # - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  # - docker login -u DOCKER_LOGIN" -p DOCKER_PASSWORD
  - echo $DOCKER_PASSWORD | winpty docker login --username $DOCKER_LOGIN --password-stdin
  - docker push kabaconde/symfony-devops;
deploy:
  provider: script
  script: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && make push-image
  on:
    branch: master

notifications:
  email: false
