version: "3.6"
services:
    apache:
        build: ./docker/apache
        container_name: devops
        volumes:
            - ./docker/apache/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/symfony:cached
        expose:
            - 80
        networks:
            - ot_network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.devops.rule=Host(`${PRODUCTION_DOMAIN_NAME}`)"
            - "traefik.http.routers.devops.tls.certresolver=leresolver"
            - "traefik.http.routers.devops.entrypoints=websecure"

    elasticsearch:
        container_name: sb-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
        expose:
            - 9200
        networks:
            - ot_network
        environment:
            - "discovery.type=single-node"
            - "bootstrap.memory_lock=true"
            - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
            - "xpack.security.enabled=false"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=*"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.elastic.rule=Host(`elastic.kabaconde.com`)"
            - "traefik.http.routers.elastic.tls.certresolver=leresolver"
            - "traefik.http.routers.elastic.entrypoints=websecure"

    # kibana (official image)
    # https://hub.docker.com/_/kibana
    kibana:
        container_name: sb-kibana
        image: docker.elastic.co/kibana/kibana:6.8.6
        expose:
            - 5601
        environment:
            - "ELASTICSEARCH_URL=http://sb-elasticsearch"
        depends_on:
            - elasticsearch
        networks:
            - ot_network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kibana.rule=Host(`kibana.kabaconde.com`)"
            - "traefik.http.routers.kibana.tls.certresolver=leresolver"
            - "traefik.http.routers.kibana.entrypoints=websecure"
networks:
  ot_network:
    external: true
